version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER: corts    
  DOCKER_PASS:
    secure: ATrglohIlg/NHRCeHMytmg==
    
install:
  - ps: .\update-docker-ce.ps1
  - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"

build_script:
  - ps: .\build.ps1

test_script:
  - ps: .\test.ps1

deploy_script:
  - ps: .\deploy.ps1
