version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER: victors2
  DOCKER_PASS:
    secure: kgpRGG5woa2ZoXDFtIF+8w==
    
install:
  - docker version
  # the official way to update to Docker 1.13.1 CS
  # - ps: Install-Package -Name docker -ProviderName DockerMsftProvider -Verbose -Update -Force
  # - ps: Start-Service docker
  # the faster way to update to Docker 1.13.1 CS
  - ps: >-
      $ProgressPreference = 'SilentlyContinue';
      Invoke-WebRequest -Outfile $env:TEMP\docker-1.13.1.zip https://dockermsft.blob.core.windows.net/dockercontainer/docker-1-13-1.zip -UseBasicParsing;
      Stop-Service docker;
      Expand-Archive $env:TEMP\docker-1.13.1.zip -DestinationPath $env:ProgramFiles -Force;
      Start-Service docker
  - docker version
  - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"

build_script:
  - ps: .\build.ps1

test_script:
  - ps: .\test.ps1

deploy_script:
  - ps: .\deploy.ps1
