version: 1.0.{build}
image: Windows Server 2016

environment:
  DOCKER_USER:
    secure: LjNiW/ZWrfVIJn3Mc9foeg==
  DOCKER_PASS:
    secure: 4gsl5WiqIztEWhL5fuhp9X0qT/mKg9fYzKYUUPf5WStIuNddv0fvIKGmvvyuFzzd
install:
  - docker version
  # the official way to update to Docker 1.13.1 CS
  # - ps: Install-Package -Name docker -ProviderName DockerMsftProvider -Verbose -Update -Force
  # - ps: Start-Service docker
  # the faster way to update to Docker 1.13.1 CS
  - ps: >-
      $ProgressPreference = 'SilentlyContinue';
      Invoke-WebRequest -Outfile $env:TEMP\docker-1.13.1.zip https://dockermsft.blob.core.windows.net/dockercontainer/docker-1-13-1.zip -UseBasicParsing;
      Stop-Service docker;
      Expand-Archive $env:TEMP\docker-1.13.1.zip -DestinationPath $env:ProgramFiles -Force;
      Start-Service docker
  - docker version

build_script:
  - ps: .\build.ps1

test_script:
  - ps: .\test.ps1

deploy_script:
  - ps: .\deploy.ps1
